#!/usr/bin/env bash 

BAD=""


for i in ` cd json_schema ; echo *.jsc ` 
do
    echo ""
    echo "working on schema $i"
    ( cd json_schema ; ../quick_schema_regresssor $i )
    URET="$?"
    echo "URET ($URET)"

    if [ "$URET" != "0" ]
    then 
        BAD="yes"
    fi

    echo ""
    echo ""
done


if [ "${BAD}" == "" ] 
then 
    echo "SUCCESS!!!"
    echo ""
    echo ""
else
    echo "AT LEAST ONE FAILURE" 
    echo ""
    echo ""
    exit 1 
fi
