#!/usr/bin/env perl 

# do_a_page $PAGENUM $entries

my ($pagenum,$entries) = @ARGV; 

if (not defined $pagenum){
	die("need pagenum\n");
}

$fname = "orgs.t.p.$pagenum.json"; 

`./ntimes $entries > $fname `; 
exec ("vi $fname");
