# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-05 03:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20160505_0251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Example',
        ),
    ]
