# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 07:41
from __future__ import unicode_literals

from django.db import migrations
import django_smalluuid.models


class Migration(migrations.Migration):

    dependencies = [
        ('lighten_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='uuid',
            field=django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(version=1), unique=True),
        ),
    ]
