# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-05 02:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_example'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='example',
            name='json',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
