#!/usr/bin/env bash 

for i in orgs.t.*.json 
do
    cat "$i" | sed 's/"mday"/"day"/g'  | sed 's/"Mon"/"Monday"/g'  | sed 's/"Tue"/"Tuesday"/g' | sed 's/"Wed"/"Wednesday"/g'| sed 's/"Thu"/"Thursday"/g'| sed 's/"Fri"/"Friday"/g'| sed 's/"Sat"/"Saturday"/g'| sed 's/"Sun"/"Sunday"/g' > $i.tmp
    diff $i $i.tmp
    mv $i.tmp $i
done

exit 0;

  556  cat orgs.t.p.201.json | sed 's/"mday"/"day"/g' 
  557  cat orgs.t.p.201.json | sed 's/"mday"/"day"/g'  > orgs.t.p.201.json.tmp
  558  diff orgs.t.p.201.json orgs.t.p.201.json.tmp
  559  cat orgs.t.p.201.json | sed 's/"Mon"/"Monday"/g'  > orgs.t.p.201.json.tmp
  560  diff orgs.t.p.201.json orgs.t.p.201.json.tmp
  561  history > fixit
   62  ./gulfie_args.pm --bist > fo
   63  ./gulfie_args.pm --bist > fo
   64  vi fo
   65  vi fo
   66  vi fo
   67  ./gulfie_args.pm --bist > fo
   68  ./gulfie_args.pm --bist > fo
   69  less fo
   70  less fo
   71  ./gulfie_args.pm --bist > fo
   72  less fo
   73  ./gulfie_args.pm --bist > fo
   74  less fo
   75  ./gulfie_args.pm --bist > fo2
   76  less fo2
   77  ./gulfie_args.pm --bist > fo2
   78  less fo2 
   79  pwd
   80  ./gulfie_args.pm --bist > fo2
   81  ./gulfie_args.pm --bist > fo2
   82  less of
   83  less fo2
   84  ./gulfie_args.pm --bist
   85  ./gulfie_args.pm --bist
   86  ./gulfie_args.pm --bist
   87  ./gulfie_args.pm --bist
   88  ./gulfie_args.pm --bist
   89  ls -arlt 
   90  less gulfie_args.pm
   91  ./gulfie_args.pm --bist
   92  vi ~/notes_uckah
   93  clear
   94  www.kipofu
   95  clear
   96  ls -arlt 
   97  clear
   98  ls -arlt 
   99  pwd
  100  cd /Users/x/fp/sfor/heroku/lighten-django-demo
  101  ls -arlt 
  102  docker ps
  103  docker-machine create default --driver virtualbox
  104  docker ps 
  105  docker-machine ps
  106  docker-machine --help 
  107  docker-machine ls 
  108  docker-machine restart default 
  109  docker-machine ls 
  110  docker ps 
  111  pwd
  112  docker-compose up web 
  113  won
  114  won
  115  won
  116  won
  117  won
  118  won
  119  won
  120  cd images
  121  ls -arlt 
  122  ls -arlt 
  123  cd pic_tree_Imgur_\ The\ most\ awesome\ images\ on\ the\ Internet.html 
  124  won
  125  won
  126  clear
  127  ls -arlt 
  128  clear
  129  ls -arlt 
  130  bc -l 
  131  pwd
  132  df -lk . 
  133  locate Bomber
  134  locate sleep 
  135  locate sleep  | egrep mp4
  136  locate sleep  | egrep 4
  137  cd
  138  cd Downloads
  139  ls -arlt 
  140  ls *eep*
  141  todo
  142  won
  143  won
  144  won
  145  won
  146  todo
  147  won
  148  won
  149  won
  150  won
  151  won
  152  won
  153  won
  154  won
  155  clear
  156  ls -arlt 
  157  pwd
  158  cd
  159  cd fp/jobs/2016/
  160  ls -arlt 
  161  bin/stamp box
  162  bin/vn box
  163  bc -l 
  164  bc -l 
  165  cat ~/people/gulfie | less
  166  todo
  167  won
  168  won
  169  won
  170  won
  171  won
  172  won
  173  won
  174  won
  175  won
  176  won
  177  won
  178  won
  179  won
  180  won
  181  won
  182  won
  183  won
  184  won
  185  won
  186  won
  187  won
  188  won
  189  won
  190  won
  191  won
  192  won
  193  won
  194  bc -l 
  195  ls -arlt 
  196  won
  197  won
  198  won
  199  won
  200  won
  201  won
  202  won
  203  ls -arlt 
  204  pwd
  205  clear
  206  ls -arlt 
  207  pwd
  208  pwd
  209  cd fp/
  210  ls -arlt 
  211  cd
  212  cd Downloads
  213  ls -arlt 
  214  ls *eep*
  215  ls *Bomb*
  216  ls *fort*
  217  ls -arlt 
  218  pwd
  219  won
  220  won
  221  won
  222  won
  223  won
  224  won
  225  clear
  226  ls -arlt 
  227  todo
  228  clear
  229  ls -arlt 
  230  ls -arlt 
  231  kipofu
  232  won
  233  won
  234  won
  235  won
  236  won
  237  won
  238  won
  239  won
  240  won
  241  sudo ./bash_stub_root 
  242  sudo ./bash_stub_root 
  243  cd
  244  cd fp/python/
  245  mv ~/Downloads/google-python-exercises* .
  246  cd google-python-exercises
  247  ls a-rlt 
  248  ls -arlt 
  249  find . 
  250  cd basic/
  251  ls -arlt 
  252  cat alice.txt 
  253  ls -alrt 
  254  cd ../
  255  ls -arlt 
  256  cd ../../
  257  ls -arlt 
  258  cd python/
  259  ls -arlt 
  260  python
  261  which python
  262  /usr/bin/python
  263  ls -arlt /usr/local/bin/python
  264  pushd .
  265  cd fp/sfor/dj
  266  cd
  267  cd fp/sfor/heroku
  268  ls
  269  . venv/bin/activate
  270  python
  271  cd / 
  272  cd
  273  ls -arlt 
  274  cd /opt/local/bin/python3.4
  275  pwd
  276  cd -
  277  cd
  278  cd fp/sfor/
  279  ls -arlt 
  280  pwd
  281  cd heroku
  282  ls -arlt 
  283  cd lighten-django-demo/
  284  ls
  285  cat notes 
  286  docker-compose run web bash 
  287  cd
  288  cd fp/python/
  289  ls -arlt 
  290  python3.4
  291  ls -arlt pwd
  292  pwd
  293  cd
  294  ls -arlt 
  295  reset
  296  ls -arlt 
  297  cd fp/sfor/heroku/lighten-django-demo/
  298  ls
  299  ls -arlt 
  300  find . -name "*db*"
  301  python -m hello/management/commands/db3.py 
  302  python -m hello/management/commands/db3
  303  ls -arlt 
  304  clear
  305  ls -arlt 
  306  ls -arlt 
  307  python db2_test.py 
  308  find . -name "*db*"
  309  python hello/db_tool.py 
  310  python hello/management/commands/db3.py 
  311  pwd
  312  pwd
  313  python hello/management/commands/db3.py 
  314  python hello/management/commands/db3.py 
  315  python hello/management/commands/db3.py 
  316  python hello/management/commands/db3.py 
  317  pwd
  318  pwd
  319  cd home
  320  cd hello/
  321  python db6.py 
  322  vi ~/notes_uckah
  323  vi ~/notes_uckah
  324  python db6.py 
  325  python db6.py 
  326  python db6.py 
  327  python db6.py 
  328  python db6.py 
  329  python db6.py 
  330  python db6.py 
  331  vi models.py
  332  export DJANGO_SETTINGS_MODULE="/Users/x/fp/sfor/heroku/lighten-django-demo/hello/../gettingstarted/settings.py"
  333  python db7.py 
  334  python db7.py 
  335  python db7.py 
  336  python db7.py 
  337  ls
  338  pwd
  339  pwd
  340  python db7.py 
  341  python db7.py 
  342  python db7.py 
  343  python db7.py 
  344  python db7.py 
  345  python db7.py 
  346  python db7.py 
  347  python db7.py 
  348  python db7.py 
  349  python db7.py 
  350  find . -type f | xargs egrep 'defaults'
  351  find . -type f | xargs egrep -i 'defaults'
  352  find . -type f | xargs egrep -i 'sett'
  353  vi ../gettingstarted/settings.py
  354  q
  355  vi ../gettingstarted/settings.py
  356  python db7.py 
  357  vi ../gettingstarted/settings.py
  358  python db7.py 
  359  vi /Users/x/f/p/sfor/heroku/venv/lib/python2.7/site-packages/django/db/models/base.py 
  360  python db7.py 
  361  vi /Users/x/f/p/sfor/heroku/venv/lib/python2.7/site-packages/django/db/models/base.py 
  362  vi /Users/x/f/p/sfor/heroku/venv/lib/python2.7/site-packages/django/db/models/base.py 
  363  python db7.py 
  364  vi /Users/x/f/p/sfor/heroku/venv/lib/python2.7/site-packages/django/db/models/base.py 
  365  python db7.py 
  366  vi /Users/x/f/p/sfor/heroku/venv/lib/python2.7/site-packages/django/db/models/base.py 
  367  python db7.py 
  368  vi /Users/x/f/p/sfor/heroku/venv/lib/python2.7/site-packages/django/db/models/base.py 
  369  python db7.py 
  370  vi /Users/x/f/p/sfor/heroku/venv/lib/python2.7/site-packages/django/db/models/base.py 
  371  python db7.py 
  372  vi /Users/x/f/p/sfor/heroku/venv/lib/python2.7/site-packages/django/db/models/base.py 
  373  python db7.py 
  374  vi /Users/x/f/p/sfor/heroku/venv/lib/python2.7/site-packages/django/db/models/base.py 
  375  python db7.py 
  376  vi /Users/x/f/p/sfor/heroku/venv/lib/python2.7/site-packages/django/db/models/base.py 
  377  find /Users/x/f/p/sfor/heroku/venv/lib/python2.7/site-packages/django/ -type f | xargs egrep '/Users/x/f/p/sfor/heroku/venv/lib/python2.7/site-packages/django/'
  378  find /Users/x/f/p/sfor/heroku/venv/lib/python2.7/site-packages/django/ -type f | xargs egrep '
  379  vi /Users/x/f/p/sfor/heroku/venv/lib/python2.7/site-packages/django/db/models/base.py 
  380  find /Users/x/f/p/sfor/heroku/venv/lib/python2.7/site-packages/django/ -type f | xargs egrep 'get_containing_app_config/
  381  find /Users/x/f/p/sfor/heroku/venv/lib/python2.7/site-packages/django/ -type f | xargs egrep 'get_containing_app_config'
  382  vi 
  383  find /Users/x/f/p/sfor/heroku/venv/lib/python2.7/site-packages/django/ -type f | xargs egrep 'get_containing_app_config'
  384  vi /Users/x/f/p/sfor/heroku/venv/lib/python2.7/site-packages/django//apps/registry.py 
  385  q
  386  vi /Users/x/f/p/sfor/heroku/venv/lib/python2.7/site-packages/django//apps/registry.py 
  387  vi /Users/x/f/p/sfor/heroku/venv/lib/python2.7/site-packages/django/db/models/base.py 
  388  python db7.py 
  389  ls -arlt 
  390  pwd
  391  export
  392  export | egrep SET
  393  unset DJANGO_SETTINGS_MODULE
  394  ls -arlt 
  395  python db7.py 
  396  pwd
  397  find ../../ -type f "*setting*"
  398  find ../../ -type f -name "*setting*"
  399  less ../..//venv/lib/python2.7/site-packages/django/conf/global_settings.py
  400  pwd
  401  export DJANGO_SETTINGS_MODULE="/Users/x/fp/sfor/heroku/lighten-django-demo/hello/../..//venv/lib/python2.7/site-packages/django/conf/global_settings.py"
  402  python db7.py 
  403  export DJANGO_SETTINGS_MODULE="/Users/x/fp/sfor/heroku/lighten-django-demo/hello/../..//venv/lib/python2.7/site-packages/django/conf/global_settings"
  404  python db7.py 
  405  export DJANGO_SETTINGS_MODULE="/Users/x/fp/sfor/heroku/lighten-django-demo/hello/../..//lighten-django-demo/gettingstarted/settings.py"
  406  python db7.py 
  407  ls
  408  cp ../gettingstarted/settings.py clisettings.py
  409  export DJANGO_SETTINGS_MODULE="clisettings"
  410  python db7.py 
  411  ls -arlt 
  412  egrep hello * 
  413  vi clisettings.py
  414  egrep module *
  415  egrep module *
  416  python db7.py 
  417  cd ../
  418  python hello/db7.py 
  419  l s-arlt 
  420  ls -arlt 
  421  cd hello/
  422  ls -arlt 
  423  mkdir clitool 
  424  cp db7.py clitool/db8.py
  425  cd clitool/
  426  ls -arlt 
  427  touch __init__.py
  428  python db8.py 
  429  pwd
  430  mv ../clisettings.py .
  431  python db8.py 
  432  touch hello.py
  433  python db8.py 
  434  vi ../../gettingstarted/settings.py
  435  python db8.py 
  436  python db8.py 
  437  cd ../
  438  ls -arlt 
  439  pwd
  440  find ../ -type f | xargs egrep 'db7'
  441  pwd
  442  cd clitool/
  443  vi clisettings.py
  444  python db8.py 
  445  kill %1
  446  python db8.py 
  447  kill %1
  448  python db8.py 
  449  kill %1
  450  export
  451  vi bash_stub
  452  which bash 
  453  vi bash_stub
  454  chmod +x ./bash_stub 
  455  ./bash_stub 
  456  kill %1
  457  ./bash_stub 
  458  kill %2
  459  sudo ./bash_stub 
  460  kill %1
  461  sudo kill -9 48025
  462  sudo dtruss ./bash_stub 
  463  sudo dtruss -f  ./bash_stub 
  464  cp bash_stub bash_stub_root
  465  vi bash_stub_root 
  466  sudo bash_stub_
  467  sudo bash_stub_root 
  468  sudo ./bash_stub_root 
  469  script dtruss1.log
  470  script dtruss2.log
  471  less dtruss1.log 
  472  ls -arlt 
  473  sudo bash_stub_root 
  474  ./bash_stub_root 
  475  ./bash_stub
  476  kill %1
  477  ls -arlt 
  478  find ../../../ -type f | xargs egrep 'setup'
  479  find ../../../ -type f -name "*.py" | xargs egrep 'setup' | egrep def 
  480  find ../../../ -type f -name "*.py" | xargs egrep 'setup' | egrep def | less
  481  less ../../..//venv/lib/python2.7/site-packages/django/__init__.py
  482  kipofu
  483  clear
  484  ls -arlt 
  485  clear
  486  ls -arlt 
  487  cd fp/jobs/2016/
  488  ls -arlt 
  489  cd data/netskope/
  490  ls -arlt 
  491  vi notes 
  492  vi notes 
  493  pwd
  494  cd ../
  495  cd ../
  496  ls -arlt 
  497  bin/stamp taos
  498  vi data/taos/notes 
  499  kipofu
  500  vi ~/people/lighten_superuser
  501  cd /Users/x/fp/sfor/heroku/lighten-django-demo/data/json1/json_schema
  502  ls -arlt 
  503  vi orgs.t.p.100.json 
  504  vi README
  505  pwd
  506  ls -arlt 
  507  ls -arlt 
  508  egrep mday * 
  509   egrep 'hours_atom' * 
  510  ls -arlt 
  511  vi hours.
  512  vi hours.jsc
  513  vi hours.jsc
  514   egrep 'hours_atom' * 
  515  egrep hours_atom * 
  516  egrep hours_atom *.jsc
  517  vi basic_components.jsc
  518  ls -arlt 
  519  vi README 
  520  ls a-rlt 
  521  cd ../
  522  pwd
  523  ls a-rlt 
  524  ls -arlt 
  525  cd json_schema/
  526  ls
  527  vi contact.jsc
  528  vi basic_components.jsc
  529  vi basic_components.jsc
  530  vi basic_components.jsc
  531  pwd
  532  vi basic_components.jsc
  533* 
  534  ls -arlt 
  535  vi contact.t.p.1 
  536  cat contact.t.p.1 
  537  cat contact.t.p.2
  538  cat contact.t.f.1 
  539  cat contact.t.f.2
  540  cat contact.t.f.3
  541  ls -arlt 
  542  vi orgs.t.p.83.json 
  543  cat contact.t.p.2
  544  vi contact.t.p.2
  545  vi basic_components.jsc
  546  vi contact.t.f.3 
  547  vi contact.t.f.3 
  548  ls -arlt 
  549  vi basic_components.jsc
  550  vi hours.t.p.2 
  551  vi hours.t.*
  552  for i in hours.t.*; do echo $i ; vi $i; done
  553  ls a-rlt 
  554  ls -arlt 
  555  ls -artl 
