#!/usr/bin/env perl

$n =1;

if ( defined $ARGV[0]){
	$n = $ARGV[0];
}

print "[\n"; 

		   #orgs.t.p.shell.json
$buf = ( `cat orgs.t.p.shell.json` ); 
print join "," , map { $buf } 1 .. $n ; 
print "]\n";


